### ISSUE TITLE
AudioParam.setValueCurveAtTime()

### ISSUE THREAD

**Issue by bthj** [ircam-ismm/node-web-audio-api#10]
The `setValueCurveAtTime()` method of the [AudioParam](https://developer.mozilla.org/en-US/docs/Web/API/AudioParam) interface doesn't seem to be bound to [the Rust implementation](https://github.com/orottier/web-audio-api-rs/blob/ead9c45fba4c49f9327f2df3e8f9c5bee066a981/src/param.rs#L515) yet.

Tried adding this to the template:

https://github.com/ircam-ismm/node-web-audio-api/compare/main...bthj:node-web-audio-api:feature/set_value_curve_at_time

but haven't figured out how to map the `JsTypedArray` to `&[f32]`.  Do you know how?

**Comment by bthj** [comment]
Seems to be working with the latest commit to 
https://github.com/ircam-ismm/node-web-audio-api/compare/main...bthj:node-web-audio-api:feature/set_value_curve_at_time

Opened a PR with this:  https://github.com/ircam-ismm/node-web-audio-api/pull/12

**Comment by b-ma** [comment]
fixed in https://github.com/ircam-ismm/node-web-audio-api/pull/12
