### ISSUE TITLE
OfflineAudioContext: reuse or clean memory resources

### ISSUE THREAD

**Issue by bthj** [ircam-ismm/node-web-audio-api#133]
Hi!

When performing consecutive renders with the OfflineAudioContext, memory usage only accumulates, for example with repeated calls like below (ran with the `--expose-gc` flag).

It might seem like an approach to reuse the OfflineAudioContext instance (e.g. by instantiating it outside the loop), but that results in an error after the first iteration. Uncommenting the suspend / resume calls also results in an error after a few iterations.

Do you see any options to clean up the used resources in this example? - or would some modifications to the library be required?

```
import { OfflineAudioContext } from 'node-web-audio-api';

for( let i=0; i < 100000; i++ ) {
  console.log('+ i:', i);

  let offline = new OfflineAudioContext(1, 10*48000, 48000);
  
  // offline.suspend(128 / 48000).then(async () => {
    const osc = offline.createOscillator();
    osc.connect(offline.destination);
    osc.frequency.value = 220;
    osc.start(0.);
    osc.stop(10.);
  
  //   await offline.resume();
  // });
  
  const buffer = await offline.startRendering();
  console.log('+ buffer duration:', buffer.duration);

  offline = null;

  if (global.gc) {
    global.gc();
  }
}
```

Running this on Apple M1 Pro

**Comment by b-ma** [comment]
Hey, thanks for the report 

From what I see after small testing the `OfflineContext` is never garbage collected, so this is a memory leak issue within the lib... The only workaround I can think of for now is to spawn / fork a new process on each iteration, very not ideal and a lot more inefficient but this should work until the issue is fixed

Still on holidays until beginning of September on my side, but I try to have a closer look as soon as possible

**Comment by bthj** [comment]
Thanks @b-ma !  

I’ll try forking for now :)

**Comment by bthj** [comment]
I've tested a [manual build](https://github.com/ircam-ismm/node-web-audio-api?tab=readme-ov-file#manual-build) on macOS after this change and it works much better 💪  and I was wondering if this could be a candidate for a release?

**Comment by b-ma** [comment]
Cool good news! I will try to release this at the end of the week, I'll let you know

**Comment by bthj** [comment]
Thank you, it works great! 

(apple silicon)
