### ISSUE TITLE
AudioBufferSourceNode not properly ended

### ISSUE THREAD

**Issue by jipodine** [ircam-ismm/node-web-audio-api#135]
After playing an AudioBufferSourceNode`src` until the end with (`src.loop = false`), there is a call to `src.onended`, as expected. However, changing `src.loop = true` plays the sound again. It means that it was properly dismissed.

**Comment by orottier** [comment]
Thanks for flagging, looking at the code it does not properly handle the case where the source has ended and subsequently a loop=true is issued:

```
// The output must change to a single channel of silence at the beginning of a render
// quantum after the time at which any one of the following conditions holds:
// 1. the stop time has been reached.
// 2. the duration has been reached.
// 3. the end of the buffer has been reached.
if scope.current_time >= self.stop_time
    || self.render_state.buffer_time_elapsed >= self.duration
    || !is_looping
        && (computed_playback_rate > 0. && buffer_time >= buffer_duration
            || computed_playback_rate < 0. && buffer_time < 0.)
{
```

We can fix it with an extra `self.ended_triggered` check. However for some reason I have not been able to reproduce this in a unit test. TBC

**Comment by b-ma** [comment]
Hey, 

Yup, we definitely miss an additional check.

Just to mention I tried to add a unit test for that (without the fix to see it fail properly):

```rs
fn test_loop_no_restart() {
    let sample_rate = 48_000.;
    let mut context = OfflineAudioContext::new(1, RENDER_QUANTUM_SIZE * 2, sample_rate);

    let mut buffer = context.create_buffer(1, 1, sample_rate);
    let data = vec![1.; 1];
    buffer.copy_to_channel(&data, 0);

    let mut src = context.create_buffer_source();
    src.connect(&context.destination());
    src.set_buffer(buffer);
    src.start_at(0.); // play in fast track

    // set src loop to true after it should have stopped
    context.suspend_sync(128. / sample_rate as f64, move |_| {
        src.set_loop(true);
    });

    let result = context.start_rendering_sync();
    let channel = result.get_channel_data(0);

    println!("{:?}", channel);
}
```

I just expected to see the second part the resulting buffer filled with `1` but it gave me this unexpected error instead:

```
thread 'node::audio_buffer_source::tests::test_loop_no_restart' panicked at src/node/audio_buffer_source.rs:582:37:
index out of bounds: the len is 1 but the index is 128
```

I didn't dig further as I didn't know where you were on that but I can have a closer look in the next days if you want

**Comment by orottier** [comment]
Nice catch. Feel free to fix. I'm not working on that part
