### ISSUE TITLE
Support modifying AudioBuffer after assigning to AudioBufferSourceNode

### ISSUE THREAD

**Issue by jadujoel** [ircam-ismm/node-web-audio-api#139]
Noticed a slight difference in how the `AudioBufferSourceNode` behaves to how it behaves in browsers.
In the browser you can assign an AudioBuffer to the source node and modify the `AudioBuffer` after starting the source node,
with the changes being reflected in the audio output.

Some use cases:
 * Immediately start a source node with a silent `AudioBuffer` of the correct length, and fill the `AudioBuffer` with data once the source audio file has been fetched, simplifying keeping sounds exactly in sync and on beat.
 * Streaming to an `AudioBufferSourceNode` by effectively using the `AudioBuffer` as a Ringbuffer, writing to it as new data comes from the stream.

Below an example 

```js
import { AudioContext, AudioBuffer } from 'node-web-audio-api'

const sampleRate = 48000

const context = new AudioContext({
  sampleRate,
  latencyHint: "playback"
})

const buffer = new AudioBuffer({
  length: sampleRate,
  numberOfChannels: 1,
  sampleRate
})

const source = context.createBufferSource()
source.connect(context.destination)
source.start()
source.onended = () => {
  context.close()
}

// expected: playing 220hz
// actual: playing 220hz
sinewave(buffer, 220)

// assigning the buffer
// after this, no matter what we do to the buffer
// the sound will still be whatever it was when we assigned it.
// in this case 220hz sinewave
source.buffer = buffer

// expected: playing 440hz
// actual: still playing 220hz
// modifying the buffer after setting it on source node does nothing
setTimeout(() => {
  sinewave(buffer, 440)
}, 500)

/**
 * @param {import('node-web-audio-api').AudioBuffer} buffer
 * @param {number} freq
 * @returns {void}
 */
function sinewave(buffer, freq) {
  for (let ch = 0; ch < buffer.numberOfChannels; ch++) {
    const data = buffer.getChannelData(ch)
    for (let i = 0; i < buffer.length; i++) {
      data[i] = Math.sin(2 * Math.PI * freq * i / sampleRate)
    }
  }
}

```

Here is an [example in browser via typescriptlang.org](https://www.typescriptlang.org/play/?#code/FAYw9gdgzgLgBFAhgWwA4BsCmAlRNNwC8cALABwAMVwoksc4E+AHvMRJgO5wCCArgBMAlmADCkFjAAUAb2BwEKDDjyYANPLjpVEEAE8AEkKYAuOACIMiPQCNEIANbngAXwCUNRvRt8AZr8wAJyI4Dm5+YTAAIT8AwNlNLAgAcxgACzMkNCxcfA0FCD5kGyCAeV9RNMQIDnQoMwBGfMVslXxXD1poeCgwPkCQAmJGSQA6EEDMVRj-IIBlPoHMKQ9e-sHxyA4QaRHMVlGBTFhjPBEIVcWN2ERA6Uv1zFHITAgjgRCVogA+ODkFPYHEDoMBQZYeFw0AD0ULg+1QmB2mAEZisemMyTgACYsRQ0gAvYAwuD2GB8RDoVHadEpbG4gnAKDGLiIABuyx8s0CajpFE6xMQUCZyQgGLg6QInLiRNhiF8+GC6SEUB5EDAcGQeAVcE4VXgnAIAnVMGNaUlsSCMvFZoQfTeOqE6HQCBgjudJR1esw7OCQn1gs9rx1BEFwo4Hz9oytxmtyoYgoIOLx+IQzM4bMwjKuTylQRCucCNDBMAAKkJkJg+tIvoRfv84MT4Yj8Ci4GixSQSMnNAKduTKS63W3qWKkwyFMTkGBhL4aZiJXACyT5Xni67aX64JBbY9QtPDWBjnulSlNEywhmpAWeZ2+a4eQBWKidYC+Pi6V3b88s9lXi2BMwIhEGY4h5XxJgARzMQpiiCNw-k0XwwGCKQsHgEA0hCCgAG4GEwgAeRd-1GGCSkCcpKmqWooFwjCAGo6Pg+sAToeABDwRB82I5JMBgSiakwdAABEOKkDCPAUBQkJQtC4CELDcPkwiC1GJJUjSRSGKYzRJLgdiYEQABtIQAF0QgAWTwNJRnPKQsTgAAqOBLPSUYAAUAElHLgcDMAg7z5NhLJlFyTAJMkyEFEhFwgA)

**Comment by b-ma** [comment]
For the use cases you describe, probably the correct implementation would be to create a whole new `AudioBuffer` and `AudioBufferSourceNode` and to schedule the start appropriately?

**Comment by padenot** [comment]
Firefox is correct, Chrome and Safari are incorrect.

This use case has historically been done by creating multiple `AudioBufferSourceNode` and scheduling them appropriately. The correct way to do this is to use an `AudioWorkletProcessor` and `SharedArrayBuffer`. 

https://github.com/padenot/ringbuf.js/tree/main/public/example/main-thread-to-audioworklet is a complete and self-contained example that does this, using a small library. https://ringbuf-js.netlify.app/example/main-thread-to-audioworklet/ is a deployment of this example.

Some details for the Chromium side in https://issues.chromium.org/issues/331237777, explaining why it's a problem.

**Comment by b-ma** [comment]
Cool thanks!

**Comment by jadujoel** [comment]
Ah okay I see, thanks for clarifying! 

Regarding SharedArrayBuffer I haven't been able to make it work when trying to support third-party websites that are not cross-origin-isolated. Scheduling another node is an option as you say, although tricker to keep track of the different timings, states and edge cases, so I've found this (apparently non-compliant) feature quite useful. Most likely will create some other custom worklet for this functionality so we can support more platforms in our software.

Best!

**Comment by padenot** [comment]
You can always `postMessage(...)` `ArrayBuffer` back and forth, it will work well.
