### ISSUE TITLE
Rust panic occurs establishing the AudioContext

### ISSUE THREAD

**Issue by andybee** [ircam-ismm/node-web-audio-api#20]
System: Intel x86 MacBook Pro
OS: macOS Monterey 12.6.5
Node.js: 18.16.0

I got the library working with your example no problem last night, but returning to the same codebase this morning it's now throwing a Rust panic:

```
% node index.mjs 
Any { .. }
panic occurred
fatal runtime error: Rust panics must be rethrown
zsh: abort      node index.mjs
```

The code in question is only instantiating the AudioContext:

```
import { AudioContext, load } from 'node-web-audio-api';

const audioContext = new AudioContext();
```

I'm not sure what has changed between the previous session and this one to break it. If I can provide any additional logging please let me know.

**Comment by b-ma** [comment]
Hey,

I just tried on node 18.16 and no problem on my side (only difference seems to be that I'm on MacOS 11.7), so I'm afraid I have no idea of what is could go wrong here...

Could you check your system audio configuration, i.e. default output, etc.?

**Comment by andybee** [comment]
Ah, that's the main change between last night and today. I was previously using my MacBook's internal speakers in a default setup, whereas today my MacBook is connected to a USB-C monitor. The default audio output in macOS is routed to the monitor speakers as I would expect.

**Comment by andybee** [comment]
I can confirm forcing the MacBook to route via the internal speakers, the code executes without a Rust panic, but when it's chosen to route via the monitor speakers it panics. If I can assist with alternative tests in this configuration to expose more about what might be panic'ing further down the stack do let me know.

**Comment by b-ma** [comment]
Nice catch, thanks!

I should make a release this week or beginning of next week where selecting input and output from the code itself should work, i.e. using `mediaDevices.enumerateDevices()` and audio context `sinkId` option, should be hopefully more stable.

Does not really explain why it crashes though, @orottier maybe you have an idea?

**Comment by andybee** [comment]
One further thing to add, which I don't know if it has an impact or not, but when the monitor speakers are selected macOS won't let me set the balance, but will with the built-in speakers, so perhaps the audio interface has some kind of limitation that the Rust code dislikes?

<img width="609" alt="Screenshot 2023-05-10 at 12 31 59" src="https://github.com/ircam-ismm/node-web-audio-api/assets/113305/c5e61eab-bb01-4162-af93-51bb0c7a380b">

<img width="611" alt="Screenshot 2023-05-10 at 12 32 05" src="https://github.com/ircam-ismm/node-web-audio-api/assets/113305/c8726efb-1cb6-44d5-aa40-d63b3c75ccf8">

**Comment by b-ma** [comment]
At first sight I don't think it has an impact, but maybe I'm mistaking. 

One way to test that would be to run the `sink_id` example from the upstream lib (https://github.com/orottier/web-audio-api-rs/). If you have some little time, it implies 1. downloading the repo, 2. install the rust toolchain (https://www.rust-lang.org/tools/install), and 3. run the following at the root of the project

```
cargo run --release --example sink_id
```

The example should allow you to switch between your different audio outputs

**Comment by orottier** [comment]
The fact that the underlying Rust library panics, but the NodeJs bindings do not expose the panic message, makes it a bit hard to troubleshoot indeed.

@b-ma I could introduce `AudioContext::try_new(.. args) -> Result<AudioContext, ErrorMessage>` on the Rust side of things. And perhaps you could call that one from the bindings, and throw a JS exception accordingly.
Alternatively, in the bindings you could wrap all fallible operations in a Rust panic handler, but I think that is less elegant.

This will take a bit of time to implement though..

**Comment by b-ma** [comment]
The panic message that is hidden by the bindings is due to some half-backed attempt (which I just removed) to catch all panic to trigger JS errors:

```rs
    // @todo - catch all panics and throw clean JS Error
    // do not uncomment until it is clean as it swallow the error message and
    // makes things event more complicated...
    //
    // std::panic::set_hook(Box::new(|panic_info| {
    //     println!("{:?}", panic_info.payload());

    //     if let Some(s) = panic_info.payload().downcast_ref::<&str>() {
    //         println!("panic occurred: {s:?}");
    //     } else {
    //         println!("panic occurred");
    //     }
    // }));
```

I still think that would be maybe not the most elegant but the best strategy, rather than duplicating all faillible method with a `try_something`.

I just removed that until its really, so at least we will have the clean Rust message in next release

**Comment by andybee** [comment]
I've run the sink example with `RUST_BACKTRACE=full cargo run --release --example sink_id` in the same conditions on my machine.

On first run, if I press return to select the AudioSinkType 'none', it panics as follows:

```
thread '<unnamed>' panicked at 'Up-mixing from 1 to 8 channels not supported', src/render/quantum.rs:509:22
stack backtrace:
   0:        0x10f98c9e6 - std::backtrace_rs::backtrace::libunwind::trace::h863be41b53c4f884
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x10f98c9e6 - std::backtrace_rs::backtrace::trace_unsynchronized::ha57069b30dcbe3f5
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10f98c9e6 - std::sys_common::backtrace::_print_fmt::h7dbf0829c4d9fd22
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x10f98c9e6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he84dde8223670de4
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x10f9a62da - core::fmt::write::h0721d4325d1d86bb
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
   5:        0x10f98a07c - std::io::Write::write_fmt::hf4d04b4d333539fa
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/io/mod.rs:1684:15
   6:        0x10f98c7ca - std::sys_common::backtrace::_print::h15efcfdd13c9c026
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x10f98c7ca - std::sys_common::backtrace::print::hed06273df3ccacbe
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x10f98df03 - std::panicking::default_hook::{{closure}}::he8c58e8d0abf03c5
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:271:22
   9:        0x10f98dc58 - std::panicking::default_hook::h8320561bf55c0290
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:290:9
  10:        0x10f98e4eb - std::panicking::rust_panic_with_hook::h38dc40cfa47552ba
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:692:13
  11:        0x10f98e404 - std::panicking::begin_panic_handler::{{closure}}::h727c67dc750b5cee
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:583:13
  12:        0x10f98ce29 - std::sys_common::backtrace::__rust_end_short_backtrace::h6848121e0bfe63be
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
  13:        0x10f98e0cd - rust_begin_unwind
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
  14:        0x10f9b59e3 - core::panicking::panic_fmt::h690b01655a033c26
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
  15:        0x10f929e6c - web_audio_api::render::quantum::AudioRenderQuantum::mix_inner::hafb71cb5fd2f7456
  16:        0x10f93b222 - web_audio_api::render::graph::Graph::render::h7c9836b7c1d4a6b6
  17:        0x10f963610 - web_audio_api::render::thread::RenderThread::render::hb64a9626d8ec0565
  18:        0x10f91eb42 - coreaudio::audio_unit::render_callback::<impl coreaudio::audio_unit::AudioUnit>::set_render_callback::{{closure}}::hf7a6496d7d9713af
  19:        0x111c9479f - _DefaultOutputAUFactory
  20:        0x111d9c513 - _AUNotQuiteSoSimpleTimeFactory
  21:        0x111c98825 - _AUGenericOutputFactory
  22:     0x7ff805e214ad - <unknown>
  23:     0x7ff805e1f205 - <unknown>
  24:     0x7ff805feb616 - <unknown>
  25:     0x7ff80434f4e1 - __pthread_start
```

On first run, if I choose 0, I do not hear the beep, but the code does not panic. I can then press return at the next prompt to "select AudioSinkType 'none'" and I then hear the beep from my monitor speakers.

Hope this is useful.

**Comment by orottier** [comment]
> 'Up-mixing from 1 to 8 channels not supported', src/render/quantum.rs:509:22

Thanks, this is very helpful. We have not implemented upmixing to 8 channel speaker layouts yet but this is something we can do with little effort

**Comment by andybee** [comment]
I was surprised my monitor presents itself as 8 channel! According to the [tech specs](https://www.apple.com/uk/studio-display/specs/) it has 4 speakers + 2 woofers. The Audio MIDI Setup app on macOS shows the 8 outputs as Front Left, Front Right, Front Centre, Low-Frequency Effects, Back Left, Back Right, Top Side Left, Top Side Right.

I'm now intrigued how most other apps on macOS cope with that!

**Comment by orottier** [comment]
Thanks, I have changed the default channel count for online AudioContext to 2 in https://github.com/orottier/web-audio-api-rs/pull/275 while still allowing users to change it to 8 if the hardware supports it.

**Comment by andybee** [comment]
I can confirm v0.9.0, which in turn bumps the upstream crate to v0.30, resolves this issue for me. Thank you!

**Comment by b-ma** [comment]
cool, thanks for the feedback!
