### ISSUE TITLE
Connect method on AudioNodes

### ISSUE THREAD

**Issue by orottier** [ircam-ismm/node-web-audio-api#3]
I've had a look at the `connect` setup you are using for AudioNodes. It's quite clever with the macro but indeed maybe not the best way forward. Especially if you also need to implement the `connect_at` and `disconnect` methods.. Unfortunately I can't really come up with any better way.

My idea would be to implement the `AudioNode` trait for the Napi wrapper types you have defined (e.g. NapiGainNode). That should be trivial because you can delegate the four required methods to the Rc'd inner value. Then, I was looking for a napi method to downcast to a trait object instead of a specific type. I could not find it unfortunately. By downcasting to a `dyn AudioNode` you should be able to eliminate all the duplicate code per specific type.

There may be a solution similar to the one presented in #2 but I don't think that makes life much better.
To be continued later..

**Comment by b-ma** [comment]
Ok, thanks again for having a look. Not _per se_ a good news, but at least you confirm the impression I had.

I will try to advance on the code generation from there, it's good enough for now (at least it works! :)
