### ISSUE TITLE
Support `addEventListener()`

### ISSUE THREAD

**Issue by UlyssesZh** [ircam-ismm/node-web-audio-api#31]
Currently audio nodes do not inherit `EventTarget`. Is there any chances to implement the events?

**Comment by b-ma** [comment]
Yes that would be nice indeed. Actually most events are already implemented in the upstream lib, so hopefully this is just a matter of finding time to focus on the question and to make it work with `napi-rs`.

So far, my understanding is that there no way to properly inherit things with `napi-rs` (and more generally with NAPI) so the actual/real inheritance chain would not be respected. But, I think it's no big deal as long as the final interface is right. Also, my guess is that it would be far more simpler to implement only the event attribute (e.g. `AudioBufferSourceNode.onended`) on the rust side, and delegate all the `addEventListener/removeEventListener` implementation in the JS side. If you are willing to have a closer look it's very welcome!

**Comment by b-ma** [comment]
Closing in favour of #63
