### ISSUE TITLE
new AudioContext().decodeAudioData(arrayBuffer)  throws no output device available

### ISSUE THREAD

**Issue by luliloveshe** [ircam-ismm/node-web-audio-api#34]
My machine is a server and the windows server 2012R2 operating system is installed. There is no sound card. An error occurs when executing this code。
s it necessary to install a sound card or is there any other alternative? I'm just doing audio synthesis and don't need to play it

**Comment by b-ma** [comment]
Hey, 

You should probably use an [`OfflineAudioContext`](https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext) then.

**Comment by luliloveshe** [comment]
I've used OfflineAudioContext. But there are two problems: 
1. OfflineAudioContext initialization requires 3 parameters (fixed values ​​​​set by me： new OfflineAudioContext(2, 44100 *1, 44100).decodeAudioData(arrayBuffer)）. 
2. The playback speed (source.playbackRate.value = webAudioSourceBean.speed) of the synthesized audio does not take effect.

**Comment by luliloveshe** [comment]
My development machine is Windows 10 and has a sound card. The playback speed after synthesis is normal. But when deployed to a server without a sound card, the synthesized audio speed has no effect.

**Comment by b-ma** [comment]
> The playback speed (source.playbackRate.value = webAudioSourceBean.speed) of the synthesized audio does not take effect.

This is weird and looks like an issue on its own, but this small test works properly on my side:

```js
import { AudioContext, OfflineAudioContext } from 'node-web-audio-api';
import fs from 'node:fs';

const offline = new OfflineAudioContext(1, 44100, 44100);
const buffer = await offline.decodeAudioData(fs.readFileSync('sample.wav').buffer);

const src = offline.createBufferSource();
src.buffer = buffer;
src.playbackRate.value = 2;
src.connect(offline.destination);
src.start(0);

const output = await offline.startRendering();

// playback output buffer
const context = new AudioContext();
const playback = context.createBufferSource();
playback.connect(context.destination);
playback.buffer = output;
playback.start();
```

Could you elaborate a bit more on what you are trying to achieve? Its not clear to me

In another direction, maybe you can try `new AudioContext({ sinkId: 'none' })`

**Comment by luliloveshe** [comment]
My goal is to develop an audio editor with functions such as fade in and fade out, cropping, and speed changing. The development machine Windows 10 has a sound card and all functions work normally. Deploy to the server (windows server 2012 does not have a sound card, but the virtual audio device is enabled), using two methods: new AudioContext({ ).decodeAudioData(arrayBuffer); and new OfflineAudioContext(2, 44100 * 1, 44100).decodeAudioData(arrayBuffer) , the speed changing function is invalid.
But according to your method new AudioContext({ sinkId: 'none' }), both the development machine and the server seem to be successful. thank you so much

**Comment by b-ma** [comment]
ok cool!
