### ISSUE TITLE
`decodeAudioData` does not seem to work - throws InvalidArg

### ISSUE THREAD

**Issue by kostia1st** [ircam-ismm/node-web-audio-api#51]
```ts
const context = new AudioContext({ sampleRate: 44100, latencyHint: 'interactive' });
const buf = Buffer.from([1, 2, 3]);
const audioBuffer = await context.decodeAudioData(buf);
```
At the last line I'm getting an Error with `code: 'InvalidArg'` set.

Basically, I have 2 requests: besides fixing the actual issue, I think everyone will benefit from the code throwing a more digestible error, so that you guys would have way more information to act upon.

**Comment by b-ma** [comment]
Hey, thanks for the feedback.

Actually `decodeAudioData` requires an `ArrayBuffer` as argument, bot a `Buffer` (see change in the last line):

```js
const context = new AudioContext({ sampleRate: 44100, latencyHint: 'interactive' });
const buf = Buffer.from([1, 2, 3]);
const audioBuffer = await context.decodeAudioData(buf.buffer);
```

Now the code will fail but because the given buffer is not recognized as a valid audio format, which is fine.

The type check for a  more readable error was actually broken, this is fixed in 497f60a and will be shipped in next release

**Comment by kostia1st** [comment]
Thanks for the answer. But I'm puzzled a bit.

Is this behavior by design?

Asking because
- according to TS typings, it must work with anything implementing `ArrayBuffer`'s interface, means it must have `byteLength` and be able to `.slice()`
- the competition (in the form of `web-audio-engine` and `electron`'s built-in `AudioContext`) both work with `Buffer` no issues

**Comment by b-ma** [comment]
Sorry for the late response,

Actually, the spec says that the argument should be an `ArrayBuffer`, cf. https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-decodeaudiodata

And the current behaviour seems consistent with the one of browsers:

```js
const context = new AudioContext({ sampleRate: 44100, latencyHint: 'interactive' });
const buf = new Float32Array([1, 2, 3]);
const audioBuffer = await context.decodeAudioData(buf);
```

throws `TypeError: Failed to execute 'decodeAudioData' on 'BaseAudioContext': parameter 1 is not of type 'ArrayBuffer'.`

So I don't really know why `web-audio-engine` and `electron's` accept a `Buffer`, but it doesn't feel right regarding the spec from what I understand
