### ISSUE TITLE
AudioContext setSinkId() throws invalid sink error with valid IDs

### ISSUE THREAD

**Issue by InanisOmnia** [ircam-ismm/node-web-audio-api#69]
I must start by saying how useful this library is, I have been hunting for a good node api implementation for a project for ages, so thank you for developing this masterpiece.

Having said that I am having issues with changing the sink of an instantiated AudioContext object.
No matter what ID I pass into this method I get a `UnhandledRejection Error: NotFoundError: invalid sinkId`

When I execute the exact same code in a browser, it runs fine and does in fact change audio devices

`
Windows 11 Laptop
Running in the main process of an electron application
`

Thanks in advance for any assistance you can provide

**Comment by b-ma** [comment]
Hey, thanks, happy that you find the lib useful!

Did you try to run the example `examples/sink_id.mjs` on your side, do you run into the same issue?

This is hard for me to test with windows actually as I don't have the hardware at hand. But one possible problem, and difference with browsers, I can think of at the moment is that `setSinkId` only accept a string for now, i.e. the `deviceId` attribute of a device object as returned by `mediaDevices.enumerateDevices`, e.g.:

```js
const deviceList = await mediaDevices.enumerateDevices();
const audioOutputs = deviceList.filter(d => d.kind === 'audiooutput');

audioContext.setSinkId(audioOutputs[0]); // will fail
audioContext.setSinkId(audioOutputs[0].deviceId); // should work
```

If this is not the actual issue, could send a snippet of your code, see if we can find another issue?

**Comment by InanisOmnia** [comment]
Oh my goodness, the issue was I was trying to use IDs from the renderer side `navigator.mediaDevices` which are, of course, different. 

Having now tried using the IDs from the `mediaDevices` export from the lib, it is now working perfectly

Thank you for the assistance!
