### ISSUE TITLE
Playing long song

### ISSUE THREAD

**Issue by ScreamZ** [ircam-ismm/node-web-audio-api#71]
Hello !

First i wanted to thank you for bringing this, i couldn't hope for better and you did a pretty good job, i was looking for a backend solution to play sounds for an escape room and i was relying until now on puppeteer + Chromium (which is dirty but working).

I need to mix audio volume and tracks, but i have very long songs, like 15 minutes

https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer are indicated for less than 45 secs sound and https://developer.mozilla.org/en-US/docs/Web/API/MediaElementAudioSourceNode are designed for longer sound.

I can see that https://docs.rs/web-audio-api/latest/web_audio_api/struct.MediaElement.html and https://docs.rs/web-audio-api/latest/web_audio_api/node/struct.MediaElementAudioSourceNode.html are existing but there is no example usage on JavaScript side 

So far 

```js
const audioContext = new AudioContext();
audioContext.createMediaElementSource() // Expect a `mediaElement: HTMLMediaElement`
```

How to get the `mediaElement: HTMLMediaElement` using this library ?

Ideally my audio come from filesystem, but they can also come from an URL on the local network. Any example for both ? so far I've been trying with `await audioContext.decodeAudioData(fs.readFileSync(audioTheme).buffer)` but I'm not sure its the correct way (this song is about 15 mn) and can go up to 200 mB

**Comment by b-ma** [comment]
Hey, thanks for the feedback

Actually the `HTMLMediaElement` as not been wrapped yet, but I won't have time to do such work within the next weeks

_Disclaimer: that's not something I have actually tested_

As a temporary solution, I think you could just try to use a raw `AudioBufferSourceNode`. The "less than 45 secs sound" warning is more an question of network bandwidth and memory usage (which can be constrained in browsers). In node, the question is maybe a bit less important I guess.

To be clear, the main difference is that `AudioBuffer` will have the full audio file loaded in memory while with the `HTMLMediaElement ` you are more in a streaming paradigm. Then, if you have 2 stereo files of 15mn, it basically means you will have around 300Mb of RAM used to store the 2 decoded files, that's quite a lot but should work on many platform I imagine.

**Comment by ScreamZ** [comment]
> Hey, thanks for the feedback
> 
> Actually the `HTMLMediaElement` as not been wrapped yet, but I won't have time to do such work within the next weeks
> 
> _Disclaimer: that's not something I have actually tested_
> 
> As a temporary solution, I think you could just try to use a raw `AudioBufferSourceNode`. The "less than 45 secs sound" warning is more an question of network bandwidth and memory usage (which can be constrained in browsers). In node, the question is maybe a bit less important I guess.
> 
> To be clear, the main difference is that `AudioBuffer` will have the full audio file loaded in memory while with the `HTMLMediaElement ` you are more in a streaming paradigm. Then, if you have 2 stereo files of 15mn, it basically means you will have around 300Mb of RAM used to store the 2 decoded files, that's quite a lot but should work on many platforms I imagine.

Thank you for the reply! Appreciated!

That's exactly what I thought, I compressed everything into MP3 and it ran so far. Keep up the good work and thanks :)

**Comment by b-ma** [comment]
Cool, nice to ear it worked

>  I compressed everything into MP3

You don't even have to do that, in memory the file will be decompressed anyway, so you are just loosing resources for decompression... Reading a simple `wav` file would be probably more efficient in the end
