### ISSUE TITLE
DestinationNode needs js `AudioNodeMixin` to handle panics

### ISSUE THREAD

**Issue by orottier** [ircam-ismm/node-web-audio-api#81]
From #57 the tests in `the-destinationnode-interface` fail because the `audioContext.destination.channelCount = 0;` throws a rust panic that is not wrapped by a JS error. I looked in the `js/` directory and there is no trace of DestinationNode. Should it be added?

**Comment by b-ma** [comment]
Nice catch! But trickier than expected, it seems to hide an issue with the wpt, I will investigate
