### ISSUE TITLE
OfflineAudioContext constructor with options object

### ISSUE THREAD

**Issue by bthj** [ircam-ismm/node-web-audio-api#9]
To have the [OfflineAudioContext constructor](https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext/OfflineAudioContext) accept either an `options` object or a set of parameters, I made a small modification here:

https://github.com/ircam-ismm/node-web-audio-api/compare/main...bthj:node-web-audio-api:feature/offline_audio_context_options_constructor

Should I open a pull request?

**Comment by orottier** [comment]
> maybe we could handle it at the rust level

Not in any elegant way. We cannot overload the `new` method so we would need to introduce `new_from_options`. I don't think it will give any benefit

**Comment by bthj** [comment]
Here's a PR for one way of handling this in JS: https://github.com/ircam-ismm/node-web-audio-api/pull/11

**Comment by b-ma** [comment]
fixed in https://github.com/ircam-ismm/node-web-audio-api/pull/11
