### ISSUE TITLE
PeriodicWave constructor issue

### ISSUE THREAD

**Issue by orottier** [ircam-ismm/node-web-audio-api#93]
The following works:
`new PeriodicWave(audioContext, {real: new Float32Array([1., 1.])});`

But this doesn't:
`new PeriodicWave(context, {real: [1, 1]})`

The issue arises at the rust code
```
// src/periodic_wave.rs
let real = if let Some(real_js) = options_js.get::<&str, JsTypedArray>("real")? {
    let real_value = real_js.into_value()?;   <---- this does not work!
    let real: &[f32] = real_value.as_ref();
    Some(real.to_vec())
} else {
    None
};
```

**Comment by b-ma** [comment]
Yup thanks, this is basically the kind of cases why I introduced this helper https://github.com/ircam-ismm/node-web-audio-api/blob/9942a1bbf045ab7236547bcb2f1a08b32211fa30/js/lib/cast.js#L2 (in the still to be finished / merged `AudioBuffer` PR)

See also #84
